### ISSUE TITLE
Prep for Analysis:  Getting to know the CBC and NOAA Data 

### ISSUE THREAD

**Issue by rectheworld** [DataKind-DC/audubon-cbc#36]
## TASKS
- [ ] All temperature values should be divided by 10 to be comparable with the CBC readings (noaa station measures in tenth of a degree). These values should be kept in a New field til QA is done
- [ ] Create a variable to represent the existence of any PREC recorded by the cbc

Counting: 
- [ ] Question: Getting to know the data by numbers. How many records are there? How many States? How many years? 
- [ ] Question: How many records have cbc recorded TEMP, or PREC data but do not have the corresponding NOAA data? 

 
Basic Stats and Investigations 
- [ ] Take Absolute value of temp difference 
- [ ] Plot over time to look at possible temperature difference
- [ ] Mean Difference 
For Temperature 
- [ ] Outlier Check  - who is way off, how is way off

**Comment by ijd5004** [comment]
I started doing some of this stuff already. I will formalize it into a notebook and post it before the datajam this Saturday.

**Comment by ijd5004** [comment]
Some of the temperature data has a negative sign in front of it. Do we know why?

**Comment by rectheworld** [comment]
Does it make sense for those to be a negative temperature for example -10°F?

**Comment by ijd5004** [comment]
Very possible. I will look up the locations of a few places to see if it passes the sanity check (i.e. no negatives in florida)

**Comment by ijd5004** [comment]
Looking at some of the negative temperatures in Florida. Tried to verify with a manual pull of data from a Gainesville station from the NOAA website. The temps do not match. Are we confident the NOAA temps are in a tenth of a degree F. -0.6 F is 30.92 C...so that would match if the NOAA data from Big Query was Celcius.

![image](https://user-images.githubusercontent.com/30261267/74076429-fed60a00-49e5-11ea-8bf7-8f39605ebff7.png)


[GHCND_USW00012816_1989-12-1.pdf](https://github.com/DataKind-DC/audubon-cbc/files/4173573/GHCND_USW00012816_1989-12-1.pdf)

**Comment by Frankie-Figz** [comment]
NOAA temps are in tenth of a degree Celcius.

Negative Farenheit temperature in Florida sounds highly dubious

**Comment by ijd5004** [comment]
Dubious indeed. Celcius makes much more sense.

**Comment by ijd5004** [comment]
Tasks completed:

- NOAA temperature conversion
- Logical variable for precipitation
- Take Absolute value of temp difference
- Mean Difference for Temperature
- Outlier Check - using z-scores of temperature difference between circle and station
- Counting: how many rows, how many rows where distance under 10km, how many z-score outliers, etc.

(I'm not convinced my outlier analysis is useful yet. More important is probably determining the distances, altitudes, and other measurements cutoff values between the circles and stations.)

**Comment by ijd5004** [comment]
I believe I have answered all the questions in the prompt for this issue. We will definitely need a deep dive on outliers and visualizations, though.
